### PR TITLE
add cousins in a binary tree code in c++

### PR DESCRIPTION
**Pull request by simran0963**
Added the code to check if 2 nodes within a given binary tree are cousins or not. it uses the depth first search technique to traverse the binary tree and calculate the corresponding levels as well as the parents of the nodes we need to check and then finally it returns the required answer if the given nodes were cousins or not.
Note that any 2 nodes in the same level need not necessary be cousins. If they have same parents then they are not considered as cousins. But id they are not on the same level as well then also they are not considered to be cousins.

### CODE REVIEW

**Comment by yesiamrajeev** [comment]
Do not DELETE any files from repository, just add your code. I hope youll keep that in mind from next time!

**Comment by simran0963** [comment]
I deleted the vscode folder which got added by mistake. Since it would have caused problems at your end, I deleted it. Don't worry apart from that no previous files were deleted.

**Comment by simran0963** [comment]
Can you also add the hacktoberfest2024 and hacktoberfest-acccepted labels to the mr

**Comment by yesiamrajeev** [comment]
Yeah thats fine, i guess someone added it by mistake.
Good job!!

**Pull request merged**
