### PR TITLE
Checking for perfect square

### PR DESCRIPTION
**Pull request by Sinch25**
A basic program to check if the number entered by the user is a perfect square using loops.

### CODE REVIEW

**Comment by Sinch25** [comment]
Could you please add the 'hacktoberfest-accepted' label as it is not showing up in my profile page. It says "not accepted"

**Comment by yesiamrajeev** [comment]
Are you sure about that?? label is already there. Let me check that with the github maintainers and then reach out to you.
If possible then mail me the screenshot.

**Comment by Sinch25** [comment]
Now it's in review. Thanks a lot btw! This is my first-ever PR. Do you have any suggestions for me? Any other way I can contribute?

**Comment by yesiamrajeev** [comment]
you really scared me!! yeah its on 7days review period after completion it'll be accepted, have patience.
Its your 1st ever hacktoberfest so no need to rush learn everything this year and from next year you should contribute to large scale projects no matter you can do that now.
you can check out some repos iv starred in my profile you can contribute to them. 
if anything goes wrong you can reach out to me!! HAPPY-HACKING!!

**Comment by Sinch25** [comment]
My bad 😅
Yes alright!
Thank you for your suggestions.

**Pull request merged**
